server:
  servlet:
    context-path: /Blog
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///simpleblog?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
#    allowMultiQueries 允许多查询
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

  #spring jpa.hibernate.ddl  对比字段的映射如果不一样及更新。
  #spring  show-sql 控制台输出sql语句  启用 SQL 语句的日志记录
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    com.zry: debug
  file:
    name: log/blog-dev.log

mybatis:
  configuration:
    map-underscore-to-camel-case: true