# 应用名称
spring:
  application:
    name: SimpleBlog
  profiles:
    active: dev
  messages:
    basename: i18n/messages
#    静态资源缓存
  resources:
    cache:
      cachecontrol:
        no-cache: false
        no-store: false
        max-age: 10000
    # 要运⽤于模板之上的模板模式。另⻅ StandardTemplate-ModeHandlers( 默认值： HTML5)
#  thymeleaf:
#    mode: HTML
  #   开启 Put 请求和 Delete 请求
  mvc:
    hiddenmethod:
      filter:
        enabled: true
